package config;

import javax.swing.*;

/**
 * Configuration of the project
 */
public class ProjectConfig {
    /* Build configuration */
    // Debug mode
    public static final boolean DEBUG = false;

    // Application manifest
    public static final String APP_TITLE = "SPTerminal";
    /**
     * SW Version config
     * Major.Minor
     * [History]
     * version 0.01: first version
     */
    public static final String VERSION = "0.01";


    // Below folders are auto-generated by program
    // Store User generated files
    public static final String USER_FOLDER = "userfile";
    public static final String SPTERMINAL_INI_PATH =  USER_FOLDER + "/" + "SPTerminal.ini";
    public static final String CACHE_FOLDER = "cache";
    public static final String COMMAND_HISTORYACHE_FOLDER = "cache";

    /* Assets */
    public static final String PLAY_ICON_PATH = "./res/img/play.png";
    public static final String STOP_ICON_PATH = "./res/img/stop.png";

    public static final int SMALL_ICON_WIDTH = 12;
    public static final int SMALL_ICON_HEIGHT = 12;
    public static final ImageIcon PLAY_ICON_SMALL =
            new ImageIcon(new ImageIcon(PLAY_ICON_PATH).getImage().getScaledInstance(SMALL_ICON_WIDTH, SMALL_ICON_HEIGHT, java.awt.Image.SCALE_SMOOTH));
    public static final ImageIcon STOP_ICON_SMALL =
            new ImageIcon(new ImageIcon(STOP_ICON_PATH).getImage().getScaledInstance(SMALL_ICON_WIDTH, SMALL_ICON_HEIGHT, java.awt.Image.SCALE_SMOOTH));

}
