package com.corochann.spterminal.config;

import javax.swing.*;

/**
 * Configuration of the project
 */
public class ProjectConfig {
    public static final int BUILD_TYPE_RUN = 1;            // build.gradle with 'run'
    public static final int BUILD_TYPE_INSTALLDIST = 2;    // build.gradle with 'installDist'
    public static final int BUILD_TYPE_RUN_MOCK_DEBUG = 3; // build.gradle with mock debug

    /* Build configuration */
    // Debug mode
    //public static final int BUILD_TYPE = BUILD_TYPE_RUN_MOCK_DEBUG; //BUILD_TYPE_RUN;
    public static final int BUILD_TYPE = BUILD_TYPE_INSTALLDIST;
    public static final boolean DEBUG = BUILD_TYPE != BUILD_TYPE_INSTALLDIST;

    /**
     * SW Version config
     * Major.Minor
     * [History]
     * version 0.01: first version
     */
    public static final String VERSION = "0.03";


    // Application manifest
    public static final String APP_TITLE = "SPTerminal";


    // Below folders are auto-generated by program
    // Store User generated files
    public static String CONFIG_ROOT_DIR = BUILD_TYPE == BUILD_TYPE_INSTALLDIST ? "../" : "./";
    public static final String USER_FOLDER = CONFIG_ROOT_DIR + "userfile/";
    public static final String LOG_FOLDER = CONFIG_ROOT_DIR + "log/";
    public static final String CACHE_FOLDER = CONFIG_ROOT_DIR + "cache/";
    public static final String RES_FOLDER = CONFIG_ROOT_DIR + "res/";

    public static final String SERIAL_PORT_CONFIG_XML_PATH =  USER_FOLDER + "SerialPortConfig.xml";
    public static final String LOG_CONFIG_XML_PATH =  USER_FOLDER + "LogConfig.xml";
    public static final String STYLE_SELECTOR_CONFIG_XML_PATH =  USER_FOLDER + "StyleConfigSelector.xml";
    /** The total path for color style xml file should be STYLE_CONFIG_PATH_PREFIX/color.xml */
    public static final String STYLE_CONFIG_PATH_PREFIX =  USER_FOLDER + "color/";
    /** The total path for Teraterm macro file (.ttl) should be TTL_PATH_PREFIX/{fileName}.ttl */
    public static final String TTL_PATH_PREFIX =  USER_FOLDER + "ttl/";

    /* Assets */
    public static final String PLAY_ICON_PATH = RES_FOLDER + "img/play.png";
    public static final String STOP_ICON_PATH = RES_FOLDER + "img/stop.png";

    public static final int SMALL_ICON_WIDTH = 12;
    public static final int SMALL_ICON_HEIGHT = 12;
    public static final ImageIcon PLAY_ICON_SMALL =
            new ImageIcon(new ImageIcon(PLAY_ICON_PATH).getImage().getScaledInstance(SMALL_ICON_WIDTH, SMALL_ICON_HEIGHT, java.awt.Image.SCALE_SMOOTH));
    public static final ImageIcon STOP_ICON_SMALL =
            new ImageIcon(new ImageIcon(STOP_ICON_PATH).getImage().getScaledInstance(SMALL_ICON_WIDTH, SMALL_ICON_HEIGHT, java.awt.Image.SCALE_SMOOTH));

    public static void setConfigRootDir (String configRootDir) {
        CONFIG_ROOT_DIR = configRootDir;
    }
}
